# application-dev.yml
springdoc:
  swagger-ui:
    enabled: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.carpick.domain.**.entity


logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG
    com.carpick.domain.car.mapper: DEBUG
