spring:
  application:
    name: carpick
  datasource:
    url: jdbc:mariadb://localhost:3306/carpick
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  web:
    resources:
      static-locations: classpath:/static/

  # ì „ì—­ì—ì„œì˜ ì—…ë¡œë“œ íŒŒì¼ í¬ê¸° ì œí•œ / ì•…ì˜ì ì¸ ìš”ì²­ ë°©ì–´ ìš©ë„
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.carpick.domain.**.entity

springdoc:
  swagger-ui:
    enabled: true
    # Swagger UIì˜ ê¸°ë³¸ ì ‘ì† ê²½ë¡œ
    path: /swagger-ui.html
    # ì»¨íŠ¸ë¡¤ëŸ¬ íƒœê·¸ë¥¼ ì•ŒíŒŒë²³ ìˆœìœ¼ë¡œ ì •ë ¬
    tags-sorter: alpha
    # ì˜¤í¼ë ˆì´ì…˜(ë©”ì„œë“œ)ì„ HTTP ë©”ì„œë“œ ìˆœìœ¼ë¡œ ì •ë ¬ (ê°œì¸ì ìœ¼ë¡œ methodë¥¼ ë” ì„ í˜¸)
    # alphaë¡œ ìœ ì§€í•´ë„ ë¬´ë°©í•©ë‹ˆë‹¤.
    operations-sorter: method
  api-docs:
    enabled: true
    # API ë¬¸ì„œë¥¼ ìœ„í•œ JSON/YAML íŒŒì¼ ê²½ë¡œ
    path: /v3/api-docs
  # APIì˜ ê¸°ë³¸ Request/Response ë¯¸ë””ì–´ íƒ€ì…ì„ JSONìœ¼ë¡œ ëª…ì‹œ
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

#openai:
#  api-key: sk-

openai:
  api-key: dummy

file:
  upload:
    path: C:/upload


# JWT ì„¤ì • ì¶”ê°€
jwt:
  secret: "mySuperSecretKeyForJWTGeneration1234567890"
  expiration: 3600000


mail:
  host: smtp.gmail.com
  port: 587
  username: "carpick001@gmail.com"  # ğŸ‘ˆ ê³µìš© ì•„ì´ë””ëŠ” ê·¸ëƒ¥ ì ì–´ë„ ë©ë‹ˆë‹¤.
  password: ${MAIL_PASSWORD}        # ğŸ‘ˆ ì—¬ê¸°ì— ì•± ë¹„ë°€ë²ˆí˜¸(16ìë¦¬)ê°€ ë“¤ì–´ê°‘ë‹ˆë‹¤.
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true